# Generated by Django 4.2.4 on 2024-10-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
